import unittest, sys
from . import get_toplevel


sys.path.insert(0, get_toplevel())
import rgit.tools # pylint: disable=wrong-import-position,wrong-import-order


class TestTools(unittest.TestCase):
	def test_url_starts_with(self):
		test_data = [
			(
				"",
				"",
				True,
			),
			(
				"//",
				"",
				True,
			),
			(
				"",
				"//",
				True,
			),
			(
				"xxx:",
				"",
				False,
			),
			(
				"",
				"xxx:",
				False,
			),
			(
				"scheme://host/",
				"//host/",
				False,
			),
			(
				"//host/path",
				"//host/",
				True,
			),
			(
				"xxx:",
				"xxx:",
				True,
			),
			(
				"//example.com",
				"xxx://example.com",
				False,
			),
			(
				"xxx://example.com",
				"//example.com",
				False,
			),
			(
				"//example.com",
				"//example.com/",
				False,
			),
			(
				"//example.com/",
				"//example.com",
				False,
			),
			(
				"/path/to/place",
				"/path/",
				True,
			),
			(
				"/path/",
				"/path/to/place",
				False,
			),
			(
				"/path/to/place",
				"/path/not/",
				False,
			),
			(
				"http://example.com/path/to/",
				"",
				False,
			),
			(
				"http://example.com/path/to/",
				"http://",
				True,
			),
			(
				"http://example.com/path/to/",
				"http:///path/to/",
				False,
			),
			(
				"http://example.com/path/to/",
				"//example.com/",
				False,
			),
			(
				"http://example.com/path/to/",
				"/",
				False,
			),
			(
				"http://example.com/path/to/",
				"http://example.com/path/to",
				True,
			),
			(
				"http://example.com/path/to/",
				"http://example.com/foo",
				False,
			),
			(
				"http://example.com/path/to/",
				"http://example.com/path",
				True,
			),
			(
				"http://example.com/path/to/",
				"https://example.com/path",
				False,
			),
			(
				"http://example.com/path/to/",
				"http://example.com/path/to/more",
				False,
			),
		]
		for url, prefix, expected in test_data:
			self.assertIs(
				rgit.tools.url_starts_with(url, prefix), expected, (url, prefix, expected)
			)
